//==============================================================================
// Hierarchical dofile generated by Conformal LEC
// Version: 20.10-p100 (01-May-2020) (64 bit executable)
//------------------------------------------------------------------------------
// The command 'set module property' sets the instance context for the current
// root module. It is intended only for hierarchical comparison, and should
// not be modified by the user.
//==============================================================================

set system mode setup
// Comparing module 'adder4to1_XW16_YW18_mydesign_3'
set root module adder4to1_XW16_YW18_mydesign_3 -Golden
set root module adder4to1_XW16_YW18_mydesign_3 -Revised
set module property -instance /wb_U0/adder_sum_r -Golden
set module property -instance /wb_U0/adder_sum_r -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box adder4to1_XW16_YW18_mydesign_3 -module -hier -Golden
add black box adder4to1_XW16_YW18_mydesign_3 -module -hier -Revised
// Comparing module 'adder4to1_XW16_YW18_mydesign_2'
set root module adder4to1_XW16_YW18_mydesign_2 -Golden
set root module adder4to1_XW16_YW18_mydesign_2 -Revised
set module property -instance /wb_U0/adder_sum_g1 -Golden
set module property -instance /wb_U0/adder_sum_g1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box adder4to1_XW16_YW18_mydesign_2 -module -hier -Golden
add black box adder4to1_XW16_YW18_mydesign_2 -module -hier -Revised
// Comparing module 'adder4to1_XW16_YW18_mydesign_1'
set root module adder4to1_XW16_YW18_mydesign_1 -Golden
set root module adder4to1_XW16_YW18_mydesign_1 -Revised
set module property -instance /wb_U0/adder_sum_g2 -Golden
set module property -instance /wb_U0/adder_sum_g2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box adder4to1_XW16_YW18_mydesign_1 -module -hier -Golden
add black box adder4to1_XW16_YW18_mydesign_1 -module -hier -Revised
// Comparing module 'adder4to1_XW16_YW18_mydesign_0'
set root module adder4to1_XW16_YW18_mydesign_0 -Golden
set root module adder4to1_XW16_YW18_mydesign_0 -Revised
set module property -instance /wb_U0/adder_sum_b -Golden
set module property -instance /wb_U0/adder_sum_b -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box adder4to1_XW16_YW18_mydesign_0 -module -hier -Golden
add black box adder4to1_XW16_YW18_mydesign_0 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_47'
set root module gamma_lut_mydesign_47 -Golden
set root module gamma_lut_mydesign_47 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R0_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R0_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_47 -module -hier -Golden
add black box gamma_lut_mydesign_47 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_46'
set root module gamma_lut_mydesign_46 -Golden
set root module gamma_lut_mydesign_46 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R0_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R0_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_46 -module -hier -Golden
add black box gamma_lut_mydesign_46 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_45'
set root module gamma_lut_mydesign_45 -Golden
set root module gamma_lut_mydesign_45 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R0_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R0_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_45 -module -hier -Golden
add black box gamma_lut_mydesign_45 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_44'
set root module gamma_lut_mydesign_44 -Golden
set root module gamma_lut_mydesign_44 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R0_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R0_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_44 -module -hier -Golden
add black box gamma_lut_mydesign_44 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_43'
set root module gamma_lut_mydesign_43 -Golden
set root module gamma_lut_mydesign_43 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R1_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R1_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_43 -module -hier -Golden
add black box gamma_lut_mydesign_43 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_42'
set root module gamma_lut_mydesign_42 -Golden
set root module gamma_lut_mydesign_42 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R1_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R1_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_42 -module -hier -Golden
add black box gamma_lut_mydesign_42 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_41'
set root module gamma_lut_mydesign_41 -Golden
set root module gamma_lut_mydesign_41 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R1_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R1_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_41 -module -hier -Golden
add black box gamma_lut_mydesign_41 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_40'
set root module gamma_lut_mydesign_40 -Golden
set root module gamma_lut_mydesign_40 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R1_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R1_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_40 -module -hier -Golden
add black box gamma_lut_mydesign_40 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_39'
set root module gamma_lut_mydesign_39 -Golden
set root module gamma_lut_mydesign_39 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R2_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R2_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_39 -module -hier -Golden
add black box gamma_lut_mydesign_39 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_38'
set root module gamma_lut_mydesign_38 -Golden
set root module gamma_lut_mydesign_38 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R2_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R2_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_38 -module -hier -Golden
add black box gamma_lut_mydesign_38 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_37'
set root module gamma_lut_mydesign_37 -Golden
set root module gamma_lut_mydesign_37 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R2_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R2_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_37 -module -hier -Golden
add black box gamma_lut_mydesign_37 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_36'
set root module gamma_lut_mydesign_36 -Golden
set root module gamma_lut_mydesign_36 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R2_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R2_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_36 -module -hier -Golden
add black box gamma_lut_mydesign_36 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_35'
set root module gamma_lut_mydesign_35 -Golden
set root module gamma_lut_mydesign_35 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R3_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R3_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_35 -module -hier -Golden
add black box gamma_lut_mydesign_35 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_34'
set root module gamma_lut_mydesign_34 -Golden
set root module gamma_lut_mydesign_34 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R3_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R3_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_34 -module -hier -Golden
add black box gamma_lut_mydesign_34 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_33'
set root module gamma_lut_mydesign_33 -Golden
set root module gamma_lut_mydesign_33 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R3_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R3_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_33 -module -hier -Golden
add black box gamma_lut_mydesign_33 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_32'
set root module gamma_lut_mydesign_32 -Golden
set root module gamma_lut_mydesign_32 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_R3_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_R3_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_32 -module -hier -Golden
add black box gamma_lut_mydesign_32 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_31'
set root module gamma_lut_mydesign_31 -Golden
set root module gamma_lut_mydesign_31 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G0_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G0_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_31 -module -hier -Golden
add black box gamma_lut_mydesign_31 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_30'
set root module gamma_lut_mydesign_30 -Golden
set root module gamma_lut_mydesign_30 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G0_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G0_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_30 -module -hier -Golden
add black box gamma_lut_mydesign_30 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_29'
set root module gamma_lut_mydesign_29 -Golden
set root module gamma_lut_mydesign_29 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G0_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G0_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_29 -module -hier -Golden
add black box gamma_lut_mydesign_29 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_28'
set root module gamma_lut_mydesign_28 -Golden
set root module gamma_lut_mydesign_28 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G0_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G0_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_28 -module -hier -Golden
add black box gamma_lut_mydesign_28 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_27'
set root module gamma_lut_mydesign_27 -Golden
set root module gamma_lut_mydesign_27 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G1_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G1_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_27 -module -hier -Golden
add black box gamma_lut_mydesign_27 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_26'
set root module gamma_lut_mydesign_26 -Golden
set root module gamma_lut_mydesign_26 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G1_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G1_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_26 -module -hier -Golden
add black box gamma_lut_mydesign_26 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_25'
set root module gamma_lut_mydesign_25 -Golden
set root module gamma_lut_mydesign_25 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G1_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G1_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_25 -module -hier -Golden
add black box gamma_lut_mydesign_25 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_24'
set root module gamma_lut_mydesign_24 -Golden
set root module gamma_lut_mydesign_24 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G1_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G1_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_24 -module -hier -Golden
add black box gamma_lut_mydesign_24 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_23'
set root module gamma_lut_mydesign_23 -Golden
set root module gamma_lut_mydesign_23 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G2_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G2_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_23 -module -hier -Golden
add black box gamma_lut_mydesign_23 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_22'
set root module gamma_lut_mydesign_22 -Golden
set root module gamma_lut_mydesign_22 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G2_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G2_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_22 -module -hier -Golden
add black box gamma_lut_mydesign_22 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_21'
set root module gamma_lut_mydesign_21 -Golden
set root module gamma_lut_mydesign_21 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G2_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G2_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_21 -module -hier -Golden
add black box gamma_lut_mydesign_21 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_20'
set root module gamma_lut_mydesign_20 -Golden
set root module gamma_lut_mydesign_20 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G2_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G2_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_20 -module -hier -Golden
add black box gamma_lut_mydesign_20 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_19'
set root module gamma_lut_mydesign_19 -Golden
set root module gamma_lut_mydesign_19 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G3_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G3_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_19 -module -hier -Golden
add black box gamma_lut_mydesign_19 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_18'
set root module gamma_lut_mydesign_18 -Golden
set root module gamma_lut_mydesign_18 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G3_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G3_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_18 -module -hier -Golden
add black box gamma_lut_mydesign_18 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_17'
set root module gamma_lut_mydesign_17 -Golden
set root module gamma_lut_mydesign_17 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G3_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G3_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_17 -module -hier -Golden
add black box gamma_lut_mydesign_17 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_16'
set root module gamma_lut_mydesign_16 -Golden
set root module gamma_lut_mydesign_16 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_G3_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_G3_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_16 -module -hier -Golden
add black box gamma_lut_mydesign_16 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_15'
set root module gamma_lut_mydesign_15 -Golden
set root module gamma_lut_mydesign_15 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B0_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B0_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_15 -module -hier -Golden
add black box gamma_lut_mydesign_15 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_14'
set root module gamma_lut_mydesign_14 -Golden
set root module gamma_lut_mydesign_14 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B0_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B0_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_14 -module -hier -Golden
add black box gamma_lut_mydesign_14 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_13'
set root module gamma_lut_mydesign_13 -Golden
set root module gamma_lut_mydesign_13 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B0_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B0_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_13 -module -hier -Golden
add black box gamma_lut_mydesign_13 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_12'
set root module gamma_lut_mydesign_12 -Golden
set root module gamma_lut_mydesign_12 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B0_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B0_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_12 -module -hier -Golden
add black box gamma_lut_mydesign_12 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_11'
set root module gamma_lut_mydesign_11 -Golden
set root module gamma_lut_mydesign_11 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B1_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B1_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_11 -module -hier -Golden
add black box gamma_lut_mydesign_11 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_10'
set root module gamma_lut_mydesign_10 -Golden
set root module gamma_lut_mydesign_10 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B1_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B1_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_10 -module -hier -Golden
add black box gamma_lut_mydesign_10 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_9'
set root module gamma_lut_mydesign_9 -Golden
set root module gamma_lut_mydesign_9 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B1_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B1_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_9 -module -hier -Golden
add black box gamma_lut_mydesign_9 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_8'
set root module gamma_lut_mydesign_8 -Golden
set root module gamma_lut_mydesign_8 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B1_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B1_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_8 -module -hier -Golden
add black box gamma_lut_mydesign_8 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_7'
set root module gamma_lut_mydesign_7 -Golden
set root module gamma_lut_mydesign_7 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B2_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B2_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_7 -module -hier -Golden
add black box gamma_lut_mydesign_7 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_6'
set root module gamma_lut_mydesign_6 -Golden
set root module gamma_lut_mydesign_6 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B2_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B2_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_6 -module -hier -Golden
add black box gamma_lut_mydesign_6 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_5'
set root module gamma_lut_mydesign_5 -Golden
set root module gamma_lut_mydesign_5 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B2_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B2_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_5 -module -hier -Golden
add black box gamma_lut_mydesign_5 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_4'
set root module gamma_lut_mydesign_4 -Golden
set root module gamma_lut_mydesign_4 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B2_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B2_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_4 -module -hier -Golden
add black box gamma_lut_mydesign_4 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_3'
set root module gamma_lut_mydesign_3 -Golden
set root module gamma_lut_mydesign_3 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B3_0 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B3_0 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_3 -module -hier -Golden
add black box gamma_lut_mydesign_3 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_2'
set root module gamma_lut_mydesign_2 -Golden
set root module gamma_lut_mydesign_2 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B3_1 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B3_1 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_2 -module -hier -Golden
add black box gamma_lut_mydesign_2 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_1'
set root module gamma_lut_mydesign_1 -Golden
set root module gamma_lut_mydesign_1 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B3_2 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B3_2 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_1 -module -hier -Golden
add black box gamma_lut_mydesign_1 -module -hier -Revised
// Comparing module 'gamma_lut_mydesign_0'
set root module gamma_lut_mydesign_0 -Golden
set root module gamma_lut_mydesign_0 -Revised
set module property -instance /gamma_U0/GAMMA_LUT_B3_3 -Golden
set module property -instance /gamma_U0/GAMMA_LUT_B3_3 -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box gamma_lut_mydesign_0 -module -hier -Golden
add black box gamma_lut_mydesign_0 -module -hier -Revised
// Comparing module 'chroma_stats_CH_NUM4_LINEAR_BW16'
set root module chroma_stats_CH_NUM4_LINEAR_BW16 -Golden
set root module chroma_stats_CH_NUM4_LINEAR_BW16 -Revised
set module property -instance /chroma_stats -Golden
set module property -instance /chroma_stats -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box chroma_stats_CH_NUM4_LINEAR_BW16 -module -hier -Golden
add black box chroma_stats_CH_NUM4_LINEAR_BW16 -module -hier -Revised
// Comparing module 'sqrt_lut'
set root module sqrt_lut -Golden
set root module sqrt_lut -Revised
set module property -instance /color_mapping/sqrt_lut -Golden
set module property -instance /color_mapping/sqrt_lut -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box sqrt_lut -module -hier -Golden
add black box sqrt_lut -module -hier -Revised
// Comparing module 'color_mapping_CH_NUM4_LINEAR_BW16'
set root module color_mapping_CH_NUM4_LINEAR_BW16 -Golden
set root module color_mapping_CH_NUM4_LINEAR_BW16 -Revised
set module property -instance /color_mapping -Golden
set module property -instance /color_mapping -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box color_mapping_CH_NUM4_LINEAR_BW16 -module -hier -Golden
add black box color_mapping_CH_NUM4_LINEAR_BW16 -module -hier -Revised
// Comparing module 'mul_IN_BW_116_IN_BW_216'
set root module mul_IN_BW_116_IN_BW_216 -Golden
set root module mul_IN_BW_116_IN_BW_216 -Revised
set module property -instance /MUL -Golden
set module property -instance /MUL -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box mul_IN_BW_116_IN_BW_216 -module -hier -Golden
add black box mul_IN_BW_116_IN_BW_216 -module -hier -Revised
// Root modules
// Comparing module 'top'
set root module top -Golden
set root module top -Revised
set module property -instance / -Golden
set module property -instance / -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;     analyze datapath -module -resourcefile ../../syn_1/report/report_resources_top.out -effort medium -verbose;     analyze datapath -flowgraph -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
report hier_compare result
report hier_compare result -Non_equivalent
report hier_compare result -Abort
report hier_compare result -Uncompared
// _END_OF_LEC_HIERARCHICAL_DOFILE_
